mail/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    # API Routes
    path("emails", views.compose, name="compose"),
    path("emails/<int:email_id>", views.email, name="email"),
    path("emails/<str:mailbox>", views.mailbox, name="mailbox"),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
	path('', views.index, name ='index'),
	path('<int:question_id>/', views.detail, name ='detail'),
	path('<int:question_id>/results/', views.results, name ='results'),
	path('<int:question_id>/vote/', views.vote, name ='vote'),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
]

polly/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

polls/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    pass


class Question(models.Model):
	question_text = models.CharField(max_length = 200)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.question_text


class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete = models.CASCADE)
	choice_text = models.CharField(max_length = 200)
	votes = models.IntegerField(default = 0)

	def __str__(self):
		return self.choice_text

polls/views.py
from django.shortcuts import render

# Create your views here.
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Question, Choice, User
import pdb
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.core.paginator import Paginator

# Get questions and display them


def login_view(request):
    if request.method == "POST":
       
        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("polls:index"))
        else:
            return render(request, "polls/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "polls/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("polls:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "polls/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "polls/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("polls:index"))
    else:
        return render(request, "polls/register.html")


def index(request):
    latest_question_list=Question.objects.order_by('-pub_date')
    paginator=Paginator(latest_question_list,5)
    page_number=request.GET.get('page')
    page_obj=paginator.get_page(page_number)
    return render(request,'polls/index.html',{'page_obj':page_obj})

# Show specific question and choices


def detail(request, question_id):
	try:
		question = Question.objects.get(pk = question_id)
	except Question.DoesNotExist:
		raise Http404("Question does not exist")
	return render(request, 'polls/detail.html', {'question': question})

#Get question and display results


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    poll_results=[]
    allchoices=Choice.objects.all().filter(question=question)
    for choice in allchoices:
        votes=choice.votes
        poll_results.append([choice.choice_text,votes])
    return render(request, 'polls/results.html', context={'question': question, "poll_results":poll_results})
	


def vote(request, question_id):
        question = get_object_or_404(Question, pk = question_id)

        poll_results = []
        try:
            selected_choice = question.choice_set.get(pk = request.POST['choice'])
        except (KeyError, Choice.DoesNotExist):
            # Redisplay the question voting form.
            return render(request, 'polls/detail.html', {
                'question': question,
                'error_message': "You didn't select a choice.",
            })
        else:
            selected_choice.votes += 1
            selected_choice.save()
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang ="en">
<head>
	<link rel ="stylesheet" href ="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
		integrity ="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin ="anonymous">
	<title>Polly {% block title %}{% endblock %}</title>
</head>

<body>
	<!--NavBar-->
	{% include 'polls/partials/_navbar.html'%}
	<div class ="container">
		<div class ="row">
			<div class =".col-md-6 m-auto">
				{% block content %}{% endblock %}
			</div>
		</div>
	</div>
</body>

</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block content %}
<a class ="btn btn-secondary btn-sm mb-3" href ="{% url 'polls:index' %}">Back To Polls</a>
<h1 class ="text-center mb-3">{{ question.question_text }}</h1>

{% if error_message %}
<p class ="alert alert-danger">
	<strong>{{ error_message }}</strong>
</p>

{% endif %}

<form action ="{% url 'polls:vote' question.id %}" method ="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
	<div class ="form-check">
		<input type ="radio" name ="choice" class ="form-check-input" id ="choice{{ forloop.counter }}"
			value ="{{ choice.id }}" />
		<label for ="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
	</div>
	{% endfor %}
	<input type ="submit" value ="Vote" class ="btn btn-success btn-lg btn-block mt-4" />
</form>



{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block content %}
{% if user.is_authenticated %}
<h1 class ="text-center mb-3">Poll Questions</h1>
{% if page_obj %}
{% for question in page_obj %}
<div class ="card-mb-3">
	<div class ="card-body">
		<p class ="lead">{{ question.question_text }}</p>

		<a href ="{% url 'polls:detail' question.id %}" class ="btn btn-primary btn-sm">Vote Now</a>
		<a href ="{% url 'polls:results' question.id %}" class ="btn btn-secondary btn-sm">Results</a>
	</div>
</div>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% else %}

<p>No polls available</p>

{% endif %}
{% else %}
<p>Login to view polls</p>
{% endif %}
{% endblock %}

polls/templates/polls/login.html
{% extends "polls/base.html" %}

{% block content %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'polls:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'polls:register' %}">Register here.</a>

{% endblock %}

polls/templates/polls/register.html
{% extends "polls/base.html" %}

{% block content %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'polls:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'polls:login' %}">Log In here.</a>

{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}
{% block content %}
<h1 class ="mb-5 text-center">{{ question.question_text }}</h1>

<ul class ="list-group mb-5">
	{% for choice in question.choice_set.all %}
	<li class ="list-group-item">
		{{ choice.choice_text }} <span class ="badge badge-success float-right">{{ choice.votes }}
			vote{{ choice.votes | pluralize }}</span>
	</li>
	{% endfor %}
</ul>

<a class ="btn btn-secondary" href ="{% url 'polls:index' %}">Back To Polls</a>
<a class ="btn btn-dark" href ="{% url 'polls:detail' question.id %}">Vote again?</a>


<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<div id="piechart"></div>


<script type="text/javascript">
  
  var poll_results = {{ poll_results|safe }};
  // Load google charts
  google.charts.load('current', { 'packages': ['corechart'] });
  google.charts.setOnLoadCallback(drawChart);

  // Draw the chart and set the chart values
  function drawChart() {
    
    poll_results.unshift(["Choice", "Vote Count"]);
    var data = google.visualization.arrayToDataTable(poll_results);

    // Optional; add a title and set the width and height of the chart
    var options = { 'width': 550, 'height': 400 };

    // Display the chart inside the <div> element with id="piechart"
    var chart = new google.visualization.PieChart(document.getElementById('piechart'));
    chart.draw(data, options);
  }
</script>

{% endblock %}